### ISSUE TITLE
Incorrect usage of tokenHoldingTime in subcategory

### ISSUE THREAD

**Issue by nitika-goel** [somish/govblocks-protocol#10]
Token holding time per sub category has been used in 2 different ways:
1. As number of seconds for which tokens should be locked under "GOV" - Validation of number of tokens locked until tokenHoldingTime in validateStake(Governance)
2. Extra time for which tokens should be locked apart from voting period - functions getMaxCategoryTokenHoldTime and  getRemainingClosingTime

An ideal approach would be tokenHoldingTime = votingTime + extraHoldingTime
and function getRemainingClosingTime = tokenHoldingTime - voting time spent

Also function getMaxCategoryTokenHoldTime() needs to be rechecked, remove if not being used.

**Comment by maxsam4** [comment]
getMaxCategoryTokenHoldTime is a vestige of the last version, no longer needed.

Why do we have tokenHoldingTime in getRemainingClosingTime in the first place? Shouldn't it just be 
getRemainingClosingTime = totalVotingtime - votingTimeSpent

**Comment by nitika-goel** [comment]
It was intended as a holdTime. For ex, holdTime = 3 days means, even if the proposal is passed, the action is not executed. Since, we are currently executing actions immediately, we might as well remove it. Let's add this feature in the advanced module post restructuring.

**Comment by nitika-goel** [comment]
Do we need function getRemainingClosingTime(). Initially, this was used to stake vote tokens for the remaining vote period. Since we are using tokenHoldingTime now, I think we can remove this as well.

**Comment by maxsam4** [comment]
getMaxCategoryTokenHoldTime was used for that.  I assumed getRemainingClosingTime was used for the UI but apparently it's not used anymore. Will remove.
