### ISSUE TITLE
Optimize ClaimReward Strategy

### ISSUE THREAD

**Issue by nitika-goel** [somish/govblocks-protocol#12]
I just noticed that there are no mappings which record proposals/solutions created by a user. While this is great as we save on gas, the claim reward function becomes very costly as we iterate through all proposals.

It is even worse for solutions, where we iterate via nested for-loops.

I suggest we do the following:
1. Take proposal numbers pending for reward as a parameter, instead of computing on blockchain. This can easily be done off-chain and we can calculate the reward to be given on-chain.
2. Maintain the proposal start variable per address, off chain.
3. Since we have all proposal ids in an array, we just raise 1 event for increasing reputation.

This shall reduce the overall complexity of the contract to a great extent.

**Comment by maxsam4** [comment]
Mappings won't help in parsing the proposals. 
However, there is no need for us to parse through all the proposals on-chain. 
We can either
1) Completely depend on off-chain for providing pending reward proposal Ids
2) Have a view function on-chain that will return the proposal Ids that have available rewards.

I am tilting towards #2 as it will take time to calculate pending proposals off-chain if we fetch data for every proposal from on-chain live. Even with the proposal start variable, we have to check every newer proposal for pending reward.

**Comment by maxsam4** [comment]
The function will take starting proposal as a param but i don't think we should be storing the lastProposalReward on chain. We should maintain the variable off chain. Basically, function 2 needs to be off chain which will have to parse through all the proposals to set the last reward id. We can do it on client side and send the param to the server.

**Comment by maxsam4** [comment]
This can be closed now.

**Comment by nitika-goel** [comment]
I agree, as mentioned earlier, we should store lastReward in database. Closing issue.
