### ISSUE TITLE
Break validateStakeAndReturnVoteValue

### ISSUE THREAD

**Issue by nitika-goel** [somish/govblocks-protocol#17]
I suggest the following:
1. Function validateStake should be marked internal and use address as a parameter to validate stake.
2. We make a separate function to calculate vote value. 
3. The functions used to caste vote use 1 and 2 separately.

I realized that because of duplicating the code we missed the condition if (subCatThenMinStake == 0) in validateStakeAndReturnVoteValue() and unnecssarily computed locked values even in case no minimum stake is required.

In my opinion, we need to weigh the amount of gas being saved vs code complexity and reusability.

**Comment by maxsam4** [comment]
Exactly why I want to restructure the code with proper internal functions and encapsulation.

**Comment by nitika-goel** [comment]
Resolved
