### ISSUE TITLE
Fetch finalVerdict details of a proposal

### ISSUE THREAD

**Issue by tech-somish** [somish/govblocks-protocol#2]
Currently the solutions event in GovernanceData contract does not have a solution id. The only way to access final verdict details is by fetching member address of final verdict, followed by filtering of the Solutions event. 
Addition of a parameter in Solutions event could hence reduce complexity.

**Comment by maxsam4** [comment]
Solution event now has solution ID and there are other ways to get the final verdict. The issue is not relevant anymore.
