### ISSUE TITLE
Auto Actions - Show Current Values

### ISSUE THREAD

**Issue by hughkarp** [somish/govblocks-protocol#32]
When completing the data inputs for automatic actions it can be easy to get the data formats incorrect.

To reduce risk it would be great to show the current value for the parameter/s being changed when values are about to be entered.

Note: I don't seem to be able to tag this for some reason. It's a enhancement, nice-to-have.

**Comment by reemaSomish** [comment]
Hi @hughkarp ! Thank you for informing us. We are taking a look at the issue!

**Comment by reemaSomish** [comment]
As per the current code :
![image (1)](https://user-images.githubusercontent.com/58204044/75952114-d1408b80-5ed3-11ea-8e69-0266262cd173.png)
