### ISSUE TITLE
Identification of external categories

### ISSUE THREAD

**Issue by nitika-goel** [somish/govblocks-protocol#6]
Currently, a category is identified as external as long as the 1st member role in _allowedToCreateProposal is 0. However, there is no check in function addNewCategory() to ensure that _allowedToCreateProposal is non-0 at all other index, say[1,0]. While this can be avoided via UI, it should be handled at the contract level as well.

**Comment by maxsam4** [comment]
Updated allowedToCreateProposal to check every position for 0.
