### ISSUE TITLE
categorizeProposal to handle AB separately

### ISSUE THREAD

**Issue by nitika-goel** [somish/govblocks-protocol#7]
The function categorizeProposal in Governance can be called either via AB or proposal owner. Both cases, should be handled in a different manner, for example validateStake() is not required in case of AB. 

Also, allowedToCreateProposal looks like a duplicate check.

**Comment by maxsam4** [comment]
Skipped validations in case of AB. allowedToCreateProposal is technically allowedToCategorizeProposal and hence, is not duplicate.
